spring:
  application:
    name: helloworld
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  paths-to-match:
    - /api/**